// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1tS7KFxY2kQk4CuoS7J44Q_BT95u5Qk0',
    appId: '1:279642591197:web:686de34dee112ff795f034',
    messagingSenderId: '279642591197',
    projectId: 'hungo-80840',
    authDomain: 'hungo-80840.firebaseapp.com',
    storageBucket: 'hungo-80840.firebasestorage.app',
    measurementId: 'G-BSN0WXG39M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFLG_eWWK5uNAWK_Xli8nr7TpoGcQpWWE',
    appId: '1:279642591197:android:f8d266a6e2cb36ba95f034',
    messagingSenderId: '279642591197',
    projectId: 'hungo-80840',
    storageBucket: 'hungo-80840.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1tS7KFxY2kQk4CuoS7J44Q_BT95u5Qk0',
    appId: '1:279642591197:web:820de84968ad92fc95f034',
    messagingSenderId: '279642591197',
    projectId: 'hungo-80840',
    authDomain: 'hungo-80840.firebaseapp.com',
    storageBucket: 'hungo-80840.firebasestorage.app',
    measurementId: 'G-YD1MJTKCJQ',
  );
}
